spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://18.218.203.150:8080"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: MyCircuitBreaker
                fallbackUri: forward:/error
        - id: analytics
          uri: lb://analytic-service
          predicates:
            - Path=/reports/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: MyCircuitBreaker
                fallbackUri: forward:/error
        - id: surveys
          uri: lb://survey-service
          predicates:
            - Path=/surveys/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: MyCircuitBreaker
                fallbackUri: forward:/error
        - id: io-service
          uri: lb://io-service
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: MyCircuitBreaker
                fallbackUri: forward:/error
        - id: submission
          uri: lb://submission-service
          predicates:
            - Path=/responses/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: MyCircuitBreaker
                fallbackUri: forward:/error

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  # if we don't say anything in 2 seconds, there is something wrong with me
  instance:
    lease-expiration-duration-in-seconds: 2
    # heartbeat every second
    lease-renewal-interval-in-seconds: 1
